export { default as Login } from './login'
export { default as Register } from './register'
export { default as Posts } from './posts'
export { default as SinglePost } from './singlePost'
export { default as AddPost} from './addPost'
export { default as Profile } from './profile'
export { default as EditPost } from './editPost'
export { default as Message } from './message'
export { default as Home } from './home'
export { default as Search } from './search'